### ISSUE TITLE
Vita turns off in sleep mode after running exploit. 

### ISSUE THREAD

**Issue by kelimz** [TheOfficialFloW/h-encore#37]
System turns off after entering sleep mode following rapidly flashing blue PS button AFTER running h-encore and installing HENkaku. This happens even if the system is plugged into power source. Tapping the power button does not wake the system and I must boot the device back up by holding down the power button as normal.

If I do not run h-encore and install HENkaku after reboot, the system does not turn off during sleep mode. 

I never experienced this issue until using this exploit. I am on FW version 3.67.

**Comment by kelimz** [comment]
Plugin conflict. Please delete. Thanks for your work, dev

**Comment by Jamsterstruk** [comment]
I'm also experiencing same issue
I'm on henkaku 3.70, since last few days I have noticed same issue 
After I launch the henkaku, once I lock the screen after few minutes only the green light near power button starts to blink and vita shuts down by itself. This happening only on henkaku but on sony stock firmware there is no such shut down..
Please help me know what plug-ins are having conflicts which is making vita behave in this manner..

**Comment by squidinkling57YT** [comment]
this has started happening to me recently, it is certainly not a plugin conflict because it happens in safe mode
