### ISSUE TITLE
H encore bootstrap menu freezes

### ISSUE THREAD

**Issue by rooster87** [TheOfficialFloW/h-encore#72]
I been in 3.65 updated to 3.57 and now 3.58 but when i open H encore to select the options it wont let me select like it freezes i formated the memory card and updated the fw. at first time trying it worked and i used enso for permanent hack and when i tried to open my micro sd2vita on vitashell it wont detected so decided to reset factory the vita and after that H encore wont let me select the options i press down and is not the buttons because outside of the hencore it works is just the app itself wont let me select.

**Comment by yodafire** [comment]
This does not happen on 3.68 I can confirm.

However, why are you using H-Encore for 3.65 FW in the first instance? You should clearly be on Enso, I am baffled as to why the Henkaku guide pushes users on 3.60/3.65 to use H-encore, when its clearly designed for OFW users with 3.67/3.68 FW.  

You should not be using H-Encore period, just un-install it and downgrade to 3.60 Enso using the down-grader, then use the app/guide to install Enso, and don't use H-Encore, its got no significance for Enso end users at all.

Yoda

**Comment by rooster87** [comment]
Ok how can i downgrade if i cant install vita shell? I manually install
vita shell it gives me the error and this is a example of my vita this link
https://youtu.be/E33Gpy4TLtQ this is not mine this is one of a few ppl with
same issue.

**Comment by TheOfficialFloW** [comment]
Please install this this using the same installation guide as in the readme: https://drive.google.com/file/d/1MnTHKLF-13_-qP7XqAqbnQ90fl3DJP4w/view?usp=sharing
Then take a video where you start h-encore and press all buttons.

**Comment by yodafire** [comment]
> Ok how can i downgrade if i cant install vita shell? I manually install vita shell it gives me the error and this is a example of my vita this link https://youtu.be/E33Gpy4TLtQ this is not mine this is one of a few ppl with same issue.

but that video indicates it was a hardware issue, not software related. clearly indicates that in the youtube readme.

either you did not remove enso properly, or your vita has a possible hardware problem.

no one on 3.68 has had this so far. I have been on on hencore since release using v1 on 3.68, no problems, just updated to v2 of hencore, no problems other than the slight plugin/compatibility issue with using DS3 on the vita based on the new fast boot without bootstrap.

i mean how come you updated to 3.68 anyway? you literally had all you could on 3.65 esp. enso. 

bey meh, try the fix above see if it works. 

i was only confused based upon why you intentionally updated your fw from 3.65 to 368 mine came pre loaded with 3.68 thats how i purchased it, so back a while ago, i could not downgrade fw had to use hencore, and literally never looked back or bothered to persist with enso.

**Comment by rooster87** [comment]
Hehe that guy he assumed it was hardware and is not he bought a diff vita i
know because my vita buttons works fine the way i updated from 3.65 to 3.68
i used the pbp update files and update from pc option on the medua manager
app.

**Comment by yodafire** [comment]
> Hehe that guy he assumed it was hardware and is not he bought a diff vita i know because my vita buttons works fine the way i updated from 3.65 to 3.68 i used the pbp update files and update from pc option on the medua manager app.

ahh okay no probs lol. 

did the fix above work?

my issue with the ds3 just got fixed ;)

**Comment by rooster87** [comment]
Ok it i bought my vita on ebay was in 3.65 i did the h encore it worked i
could select to install vita shell then i used enso to permanent worked
also when i tried to mount my sd2vita a message popped up saying pls
install sd card so i assumed i had a faulty micro sd card or the adapter or
something was wrong with the hack so i did a factory and the hack logo
popped up after the factory reset and thats where the problem began and
then updated to 3.67 the logo dissapeared to ps logo back still the hencore
frozen then updated 3.69 and still same issue.

**Comment by yodafire** [comment]
> Ok it i bought my vita on ebay was in 3.65 i did the h encore it worked i could select to install vita shell then i used enso to permanent worked also when i tried to mount my sd2vita a message popped up saying pls install sd card so i assumed i had a faulty micro sd card or the adapter or something was wrong with the hack so i did a factory and the hack logo popped up after the factory reset and thats where the problem began and then updated to 3.67 the logo dissapeared to ps logo back still the hencore frozen then updated 3.69 and still same issue.

yeah, i guess it was down to the reset, you should have removed enso prior to reset, i heard you can get a brick like that, not sure for 3.65 users, but deffo can happen on the old version of 3.60, yifan fixed that, but have not heard any issue since.

is enso still enabled on your vita? does the logo show up? or has it been removed via the hencore  install process you used on your pc?

**Comment by rooster87** [comment]
When i updated to stock ofw to 3.67 and then 3.69 im currently now the logo
of ps is back man this issue even tho we less ppl that happened to it the
creator should male something to work on it.

**Comment by TheOfficialFloW** [comment]
I asked you to test the new files but instead you write random shit that is so hard to read.

**Comment by yodafire** [comment]
> I asked you to test the new files but instead you write random shit that is so hard to read.

Sorry TF :/

won't happen again

Yoda

**Comment by rooster87** [comment]
Whoaaa chill down bro im going do it alright so chill if u going help just
chill u cant help ppl then be all agrresive all of sudden come on man.

**Comment by TheOfficialFloW** [comment]
@yodafire I didn‘t mean you but the OP.

**Comment by rooster87** [comment]
Ok so the file u gave me i just add it to the qcma software?

**Comment by rooster87** [comment]
Tried ur files it still freezes
